services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - internal_network

  backend:
    build: ./backend
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      REFRESH_SECRET_KEY: ${REFRESH_SECRET_KEY}
    depends_on:
      - db
    volumes:
        - ./backend:/app  
        - /app/__pycache__/  
    networks:
      - internal_network

  frontend:
    build:
      context: ./frontend
      args:
        CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./frontend:/app/
      - /app/node_modules 
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://backend:8000"
      CHOKIDAR_USEPOLLING: "true" 
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network: 
    driver: bridge