"""Add documentation and unique field to name

Revision ID: 4d7c1d3a2510
Revises: e28b62930a95
Create Date: 2025-03-08 22:44:07.782392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7c1d3a2510'
down_revision: Union[str, None] = 'e28b62930a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_type_name', table_name='location_type')
    op.create_index(op.f('ix_location_type_name'), 'location_type', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_type_name'), table_name='location_type')
    op.create_index('ix_location_type_name', 'location_type', ['name'], unique=False)
    # ### end Alembic commands ###
