"""add location types

Revision ID: c36f425558bc
Revises: 4399b33d8125
Create Date: 2025-03-09 15:27:49.751920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, DateTime
from sqlalchemy.sql import table, column

from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = "c36f425558bc"
down_revision: Union[str, None] = "4399b33d8125"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Define the table metadata
    location_type_table = table(
        "location_type",
        column("name", String)
    )

    # Insert data
    op.bulk_insert(
        location_type_table,
        [
            {
                "name": "Landscape",
            },
            {
                "name": "Cityscape",
            },
            {
                "name": "Park",
            },
            {
                "name": "Venue",
            },
            {
                "name": "Beach",
            },
            {
                "name": "Mountain",
            },
            {
                "name": "Riverfront",
            },
            {
                "name": "Lakeside",
            },
            {
                "name": "Island",
            },
            {
                "name": "Canyon",
            },
            {
                "name": "Valley",
            },
            {
                "name": "Forest",
            },
            {
                "name": "Plain",
            },
            {
                "name": "Other",
            },
        ],
    )
    op.execute(text("UPDATE location_type SET created_at = NOW() WHERE created_at IS NULL"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
