"""Create user location model

Revision ID: de769b0776bc
Revises: ce876fe41a4a
Create Date: 2025-03-09 15:07:28.531617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de769b0776bc'
down_revision: Union[str, None] = 'ce876fe41a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'location_id', name='uq_user_location')
    )
    op.create_index(op.f('ix_user_location_id'), 'user_location', ['id'], unique=False)
    op.create_index(op.f('ix_user_location_name'), 'user_location', ['name'], unique=False)
    op.alter_column('location', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=16),
               nullable=False)
    op.alter_column('location', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=16),
               nullable=False)
    op.alter_column('location', 'location_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_location_latitude'), 'location', ['latitude'], unique=False)
    op.create_index(op.f('ix_location_longitude'), 'location', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_longitude'), table_name='location')
    op.drop_index(op.f('ix_location_latitude'), table_name='location')
    op.alter_column('location', 'location_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('location', 'longitude',
               existing_type=sa.Float(precision=16),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('location', 'latitude',
               existing_type=sa.Float(precision=16),
               type_=sa.REAL(),
               nullable=True)
    op.drop_index(op.f('ix_user_location_name'), table_name='user_location')
    op.drop_index(op.f('ix_user_location_id'), table_name='user_location')
    op.drop_table('user_location')
    # ### end Alembic commands ###
