"""Initial migration

Revision ID: e28b62930a95
Revises: 
Create Date: 2025-03-08 21:57:49.387618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28b62930a95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_type_id'), 'location_type', ['id'], unique=False)
    op.create_index(op.f('ix_location_type_name'), 'location_type', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_type_name'), table_name='location_type')
    op.drop_index(op.f('ix_location_type_id'), table_name='location_type')
    op.drop_table('location_type')
    # ### end Alembic commands ###
